services:
  blog-strapi-backend:
    container_name: blog-strapi-backend
    # build: .
    image: blog-strapi-backend:latest
    # image: ghcr.io/quanguit/my-blog-backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: blog-strapi-backendDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      # - ./config:/opt/app/config
      # - ./src:/opt/app/src
      # - ./package.json:/opt/package.json
      # - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - blog-strapi-backend
    depends_on:
      - blog-strapi-backendDB
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  blog-strapi-backendDB:
    container_name: blog-strapi-backendDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      #- blog-strapi-backend-data:/var/lib/postgresql/data/ #using a volume
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - blog-strapi-backend

networks:
  blog-strapi-backend:
    name: Blog-strapi-backend
    driver: bridge
